line-length = 120
target-version = "py312"
preview = true

[lint]
select = [
    "F",
    "E",
    "W",
    "I",
    "UP",
    "N",
    "ASYNC",
    "B",
    "A",
    "C4",
    "FA",
    "ICN",
    "LOG",
    "G",
    "PIE",
    "PT",
    "Q",
    "RSE",
    "TC",
    "PTH",
    "NPY",
    "PERF",
    "FURB",
]
ignore = ["PIE804", "G004", "F401", "N803"]

[lint.per-file-ignores]
"__init__.py" = ["F401"]

[format]
quote-style = "double"
preview = true
